apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mongodb-services
  name: mongo-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo
